### ISSUE TITLE
RuntimeError: CUDA out of memory. Error while training in Google colab

### ISSUE THREAD

**Issue by tarunsaib1997** [salesforce/TabularSemanticParsing#38]
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/drive/My Drive/TabularSemanticParsing/src/experiments.py", line 407, in <module>
    run_experiment(args)
  File "/content/drive/My Drive/TabularSemanticParsing/src/experiments.py", line 392, in run_experiment
    train(sp)
  File "/content/drive/My Drive/TabularSemanticParsing/src/experiments.py", line 63, in train
    sp.run_train(train_data, dev_data)
  File "/content/drive/My Drive/TabularSemanticParsing/src/common/learn_framework.py", line 208, in run_train
    loss = self.loss(formatted_batch)
  File "/content/drive/My Drive/TabularSemanticParsing/src/semantic_parser/learn_framework.py", line 94, in loss
    outputs = self.forward(formatted_batch)
  File "/content/drive/My Drive/TabularSemanticParsing/src/semantic_parser/learn_framework.py", line 129, in forward
    decoder_ptr_value_ids=decoder_ptr_value_ids)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/content/drive/My Drive/TabularSemanticParsing/src/semantic_parser/bridge.py", line 50, in forward
    inputs, input_masks, segments=segment_ids, position_ids=position_ids)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/My Drive/TabularSemanticParsing/src/common/nn_modules.py", line 67, in forward
    inputs, token_type_ids=segments, position_ids=position_ids, attention_mask=(~input_masks)))
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/transformers/modeling_bert.py", line 790, in forward
    encoder_attention_mask=encoder_extended_attention_mask,
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/transformers/modeling_bert.py", line 407, in forward
    hidden_states, attention_mask, head_mask[i], encoder_hidden_states, encoder_attention_mask
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/transformers/modeling_bert.py", line 368, in forward
    self_attention_outputs = self.attention(hidden_states, attention_mask, head_mask)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/transformers/modeling_bert.py", line 314, in forward
    hidden_states, attention_mask, head_mask, encoder_hidden_states, encoder_attention_mask
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/transformers/modeling_bert.py", line 234, in forward
    attention_scores = torch.matmul(query_layer, key_layer.transpose(-1, -2))
RuntimeError: CUDA out of memory. Tried to allocate 54.00 MiB (GPU 0; 11.17 GiB total capacity; 10.35 GiB already allocated; 33.81 MiB free; 10.68 GiB reserved in total by PyTorch)

**Comment by tarunsaib1997** [comment]
Can anyone help this out?

**Comment by alan-ai-learner** [comment]
switch to colab pro, maybe it will helps? btw have to get the inference using the pretrained models provided in the repo?

**Comment by Kirubabala** [comment]
> Can anyone help this out?

Were you able to resolve this issue? I am facing the same problem.

**Comment by tarunsaib1997** [comment]
Reduced the training batch size to 2 helped.
