### ISSUE TITLE
RuntimeError when training models on WikiSQL

### ISSUE THREAD

**Issue by xinsu626** [salesforce/TabularSemanticParsing#40]
Hello, I was able to finish the training part following the commands in the README and the fix in the #17 .
But I still got the following RuntimeError during the evaluation.

Could you please give some suggestions on how I can fix it? Thank you!

```

/home/.local/lib/python3.8/site-packages/torch/nn/modules/module.py:795: UserWarning: Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using a non-full backward hook when the forward contains multiple autograd Nodes "
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 19200/19200 [30:00<00:00, 10.67it/s]
Step 399.9791666666667: average training loss = 0.7160661821833583
  0%|                                                                                                                                                                                                  | 0/4211 [00:00<?, ?it/s]

wandb: Waiting for W&B process to finish, PID 54022
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/Code/TabularSemanticParsing/src/experiments.py", line 407, in <module>
    run_experiment(args)
  File "/home/Code/TabularSemanticParsing/src/experiments.py", line 392, in run_experiment
    train(sp)
  File "/home/Code/TabularSemanticParsing/src/experiments.py", line 63, in train
    sp.run_train(train_data, dev_data)
  File "/home/Code/TabularSemanticParsing/src/common/learn_framework.py", line 241, in run_train
    output_dict = self.inference(dev_data, restore_clause_order=self.args.process_sql_in_execution_order,
  File "/home/Code/TabularSemanticParsing/src/semantic_parser/learn_framework.py", line 157, in inference
    outputs = self.forward(formatted_batch, model_ensemble)
  File "/home/Code/TabularSemanticParsing/src/semantic_parser/learn_framework.py", line 124, in forward
    outputs = self.mdl(encoder_ptr_input_ids, encoder_ptr_value_ids,
  File "/home/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/Code/TabularSemanticParsing/src/semantic_parser/bridge.py", line 54, in forward
    self.encoder(inputs_embedded,
  File "/home/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/Code/TabularSemanticParsing/src/semantic_parser/bridge.py", line 263, in forward
    schema_hiddens = self.schema_encoder(schema_hiddens, feature_ids)
  File "/home/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/Code/TabularSemanticParsing/src/semantic_parser/brwandb: Program failed with code 1. Press ctrl-c to abort syncing.
idge.py", line 166, in forward
    schema_hiddens = self.feature_fusion_layer(torch.cat([input_hiddens,
RuntimeError: Sizes of tensors must match except in dimension 1. Got 8 and 7 (The offending index is 0)
wandb: You can sync this run to the cloud by running: 
wandb: wandb sync wandb/run-20211001_050816-evuizgcy
Exception ignored in: <function _ConnectionRecord.checkout.<locals>.<lambda> at 0x7f6966c72160>
Traceback (most recent call last):
  File "/home/Code/TabularSemanticParsing/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 506, in <lambda>
  File "/home/Code/TabularSemanticParsing/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 714, in _finalize_fairy
  File "/home/Code/TabularSemanticParsing/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 531, in checkin
  File "/home/Code/TabularSemanticParsing/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in _return_conn
  File "/home/Code/TabularSemanticParsing/venv/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 238, in _do_return_conn
  File "/home/Code/TabularSemanticParsing/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 543, in close
  File "/home/Code/TabularSemanticParsing/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 645, in __close
  File "/home/Code/TabularSemanticParsing/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 267, in _close_connection
  File "/usr/lib/python3.8/logging/__init__.py", line 1433, in debug
  File "/usr/lib/python3.8/logging/__init__.py", line 1699, in isEnabledFor
TypeError: 'NoneType' object is not callable
```

**Comment by ygxw0909** [comment]
I got the same error when training models on WikiSQL. How to fix it?=-=

**Comment by xinsu626** [comment]
I fixed the bug mentioned in the above issue and then reprocessed the data and the problem was solved.

**Comment by ygxw0909** [comment]
> > I got the same error when training models on WikiSQL. Could you give me some advice about that？Thanks!
> 
> I fixed the bug mentioned in the above issue and then reprocessed the data and the problem was solved.

Thank you! Following the issue, I fixed the bug. However, another bug occurred that after some epochs of training, the loss become bigger than 1e^8, and stopped by pdb. Did you meet this problem as well?

**Comment by xinsu626** [comment]
> Thank you! Following the issue, I fixed the bug. However, another bug occurred that after some epochs of training, the loss become bigger than 1e^8, and stopped by pdb. Did you meet this problem as well?

Yes. This is the same as what I encountered. I am also wondering why suddenly loss will explode.
