### ISSUE TITLE
Training error with NaNs

### ISSUE THREAD

**Issue by sythello** [salesforce/TabularSemanticParsing#5]
Hello! Thanks for sharing the code.
I'm using a Tesla P100-PCIE-12GB GPU, which is not able to hold the model with BERT-large (raising CUDA out-of-memory error), so I have to switch to BERT-base. I also need to decrease the batch size from 16 to 8 and increase gradient accumulation steps from 2 to 4. No other changes are made to the model configuration.
When I train the model, I got the following error:
```
Traceback (most recent call last):
  File "/vault/.pyenv/versions/3.7.5/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/vault/.pyenv/versions/3.7.5/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/users/yshao/TabularSemanticParsing/src/experiments.py", line 407, in <module>
    run_experiment(args)
  File "/users/yshao/TabularSemanticParsing/src/experiments.py", line 392, in run_experiment
    train(sp)
  File "/users/yshao/TabularSemanticParsing/src/experiments.py", line 63, in train
    sp.run_train(train_data, dev_data)
  File "/users/yshao/TabularSemanticParsing/src/common/learn_framework.py", line 209, in run_train
    loss.backward()
  File "/vault/.pyenv/versions/py3.7.5-bridge/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/vault/.pyenv/versions/py3.7.5-bridge/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/vault/.pyenv/versions/py3.7.5-bridge/lib/python3.7/site-packages/wandb/wandb_torch.py", line 256, in <lambda>
    handle = var.register_hook(lambda grad: _callback(grad, log_track))
  File "/vault/.pyenv/versions/py3.7.5-bridge/lib/python3.7/site-packages/wandb/wandb_torch.py", line 254, in _callback
    self.log_tensor_stats(grad.data, name)
  File "/vault/.pyenv/versions/py3.7.5-bridge/lib/python3.7/site-packages/wandb/wandb_torch.py", line 207, in log_tensor_stats
    tensor = flat.histc(bins=self._num_bins, min=tmin, max=tmax)
RuntimeError: range of [nan, nan] is not finite
```

I also tried decreasing grad_norm from 0.3 to 0.1, but the same error occurred.
Any suggestion on the reason of this or what I can try to get rid of it? Thank you!

**Comment by todpole3** [comment]
Good catch. We run into this issue recently as well -- it appears to be an issue rooted in the wandb tool rather than the training algorithm (https://github.com/wandb/client/issues/800). 

I upgraded wandb to the latest version (0.10.15)
```
python3 -m pip install wandb --upgrade
```

Currently trying to see if the problem goes away. You could try it as well.

**Comment by sythello** [comment]
Thank you! This seems to fix the error. Although I still get "loss = nan" in the training log, the performance of the trained model is reasonable.
